# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: filestruct.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'filestruct.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x66ilestruct.proto\x12\x0c\x66iletransfer\"\x1f\n\x0b\x46ileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\".\n\tFileChunk\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\"0\n\x0cUploadStatus\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x99\x01\n\x0c\x46ileTransfer\x12\x43\n\nUploadFile\x12\x17.filetransfer.FileChunk\x1a\x1a.filetransfer.UploadStatus(\x01\x12\x44\n\x0c\x44ownloadFile\x12\x19.filetransfer.FileRequest\x1a\x17.filetransfer.FileChunk0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'filestruct_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILEREQUEST']._serialized_start=34
  _globals['_FILEREQUEST']._serialized_end=65
  _globals['_FILECHUNK']._serialized_start=67
  _globals['_FILECHUNK']._serialized_end=113
  _globals['_UPLOADSTATUS']._serialized_start=115
  _globals['_UPLOADSTATUS']._serialized_end=163
  _globals['_FILETRANSFER']._serialized_start=166
  _globals['_FILETRANSFER']._serialized_end=319
# @@protoc_insertion_point(module_scope)
